name: le_nhat_truong
description: Flutter Auth App - Spring Boot backend
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  url_launcher: ^6.3.2
  flutter_web_auth_2: ^5.0.2
  web: ^1.1.1
  image_picker: ^1.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/gg.png
    - assets/images/fb.png
    - assets/images/success_bg.png
    - assets/images/jang_wonyoung.jpg
