spring:
  profiles:
    active: postgresql
  application:
    name: authapp

  # Default profile: H2 in-memory database
  datasource:
    url: jdbc:h2:mem:authdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 866423970574-tj9c84ci6qvpd1scg3ch8g8fkoi5osn4.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          facebook:
            client-id: 1705017310534816
            client-secret: ec785c94e880559154dc4b18b4d77e77
            scope:
              - email
              - public_profile
            provider: facebook
            redirect-uri: http://localhost:8080/login/oauth2/code/facebook
      provider:
        facebook:
          authorization-uri: https://www.facebook.com/v18.0/dialog/oauth
          token-uri: https://graph.facebook.com/v18.0/oauth/access_token
          user-info-uri: https://graph.facebook.com/v18.0/me?fields=id,name,email,picture.type(large)
          user-name-attribute: id

app:
  jwt:
    secret: MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc=
    expirationMs: 3600000
    refreshExpirationMs: 604800000
  oauth2:
    authorizedRedirectUris: http://localhost:8080/oauth2/redirect.html,http://lvh.me:8080/oauth2/redirect.html,authapp://oauth2/redirect

server:
  port: 8080

---
# PostgreSQL profile: activate with --spring.profiles.active=postgresql
spring:
  config:
    activate:
      on-profile: postgresql

  datasource:
    url: jdbc:postgresql://localhost:5432/truongng
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 879779

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
